# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsf_W0PMXjrR9W_yMsJ8H6PZb0aUJyTU
"""

import sys
from pathlib import Path

# Add the current working directory to the Python path
sys.path.append(str(Path().absolute()))

!ls

import importlib
import importlib
random_forest = importlib.import_module("random_forest")
svm_model = importlib.import_module("svm_model")
lstm_model = importlib.import_module("lstm_model")

import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

# Load Breast Cancer dataset
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = y.to_numpy().reshape(-1, 1)  # Convert y to NumPy and reshape it


# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Run Random Forest model
rf_results = random_forest.random_forest_model(X_scaled, y)
print("Random Forest Results (Averaged):")
print(rf_results.mean())

# Run SVM model
svm_results = svm_model.svm_model(X_scaled, y)
print("\nSVM Results (Averaged):")
print(svm_results.mean())

# Run LSTM model
lstm_results = lstm_model.lstm_model(X_scaled, y)
print("\nLSTM Results (Averaged):")
print(lstm_results.mean())